# site info
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /post/:slug/ # consider /posts/:year/:month/:day/:title
  projects:
    output: true
    permalink: /project/:slug/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      featured_image: /images/home.jpg
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
